name: VampireZ
version: '${project.version}'
main: com.tqqn.minigames.VampireZ
api-version: '1.20'
load: STARTUP
authors: [Tqqn]
description: VampiresZ Plugin - remake of the Hypixel VampireZ
commands:
  team:
    description: Choose a Team
    usage: /<command>
  shout:
    description: Shout a message globally
    usage: /<command>
  adminstart:
    description: Admin Start Command
    usage: /<command>